name: motivation_lock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Functionality Dependencies
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  pedometer: ^4.0.0
  installed_apps: ^1.3.0
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0 # Upgraded version
  usage_stats: ^1.2.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
